### ISSUE TITLE
please update NPM for 0.10

### ISSUE THREAD

**Issue by lschierer** [nanostores/logger#20]
after upgrading nanostores from 0.9.5 to 0.10.2 and @nanostores/persistent from 0.9.1 to 0.10.1, I get the following error:

```
16:29:12 [vite] ✓ 601 modules transformed.
16:29:12 [ERROR] [vite] x Build failed in 418ms
node_modules/.pnpm/@nanostores+logger@0.2.4_nanostores@0.10.2/node_modules/@nanostores/logger/build-logger/index.js (4:2): "onAction" is not exported by "node_modules/.pnpm/nanostores@0.10.2/node_modules/nanostores/index.js", imported by "node_modules/.pnpm/@nanostores+logger@0.2.4_nanostores@0.10.2/node_modules/@nanostores/logger/build-logger/index.js".
file: /Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/@nanostores+logger@0.2.4_nanostores@0.10.2/node_modules/@nanostores/logger/build-logger/index.js:4:2
2:   actionId,
3:   lastAction,
4:   onAction,
     ^
5:   onMount,
6:   onNotify,
  Stack trace:
    at getRollupError (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/rollup@4.14.0/node_modules/rollup/dist/es/shared/parseAst.js:379:41)
    at Module.error (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/rollup@4.14.0/node_modules/rollup/dist/es/shared/node-entry.js:13685:16)
    at ModuleScope.findVariable (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/rollup@4.14.0/node_modules/rollup/dist/es/shared/node-entry.js:11819:39)
    at FunctionBodyScope.findVariable (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/rollup@4.14.0/node_modules/rollup/dist/es/shared/node-entry.js:6036:38)
    at CallExpression.bind (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/rollup@4.14.0/node_modules/rollup/dist/es/shared/node-entry.js:4752:23)
    at ReturnStatement.bind (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/rollup@4.14.0/node_modules/rollup/dist/es/shared/node-entry.js:4752:23)
    at FunctionDeclaration.bind (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/rollup@4.14.0/node_modules/rollup/dist/es/shared/node-entry.js:4752:23)
    at Module.bindReferences (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/rollup@4.14.0/node_modules/rollup/dist/es/shared/node-entry.js:13666:18)
    at Graph.build (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/rollup@4.14.0/node_modules/rollup/dist/es/shared/node-entry.js:19786:14)
    at async catchUnfinishedHookActions (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/rollup@4.14.0/node_modules/rollup/dist/es/shared/node-entry.js:19939:16)
    at async Module.build (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/vite@5.2.8_@types+node@20.12.3/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:67439:18)
    at async viteBuild (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/astro@4.5.15_@types+node@20.12.3_typescript@5.3.3/node_modules/astro/dist/core/build/static-build.js:72:24)
    at async AstroBuilder.run (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/astro@4.5.15_@types+node@20.12.3_typescript@5.3.3/node_modules/astro/dist/core/build/index.js:165:7)
    at async build (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/astro@4.5.15_@types+node@20.12.3_typescript@5.3.3/node_modules/astro/dist/cli/build/index.js:20:3)
    at async cli (file:///Users/lschiere/src/schierer/EvonyTKRTips/node_modules/.pnpm/astro@4.5.15_@types+node@20.12.3_typescript@5.3.3/node_modules/astro/dist/cli/index.js:169:5)
```

```
lschiere@80a997121f31:~/src/schierer/EvonyTKRTips$ grep nanos package.json
    "@nanostores/lit": "^0.2.1",
    "@nanostores/logger": "^0.2.4",
    "@nanostores/persistent": "^0.10.1",
    "nanostores": "^0.10.2",
lschiere@80a997121f31:~/src/schierer/EvonyTKRTips$
```

**Comment by lschierer** [comment]
This is a slightly different stack trace, but appears to be the same underlying cause as #18

**Comment by euaaaio** [comment]
I'll try to release new version yesterday.
For now, you can try to install it directly from GitHub: nanostores/logger#next

**Comment by euaaaio** [comment]
Just released v0.3.0 with a fix

**Comment by lschierer** [comment]
v0.3.0 did solve this compile error, thanks!!

**Comment by euaaaio** [comment]
Thank you for pinging me.
